package com.example.a2lab.studyone_12;

public class exam_ques_ans2 {
    public static String reading_summary1[]=new String[] {
         //reading1內文
            "With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
         //中文大綱
            ,"隨著信息和通信技術的進步，互動式多媒體學習系統被廣泛應用在教學和學習中，互動式學習系統利用多種媒體訊息來吸引學習者的注意。然而，學習者會因為人因的不同而偏好不同的設計方法，來調查學習者在使用互動式學習系統的偏好。在傳統分析資料的方式裡，資料受到假說的限制，資料探勘是根據資料的本身發現關係和模式。在此研究資料探勘的結果顯示，學習者會因為使用電腦的經驗不同而去偏好不同類型的學習功能。"
         //內文重點NO.1
            ,"1.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased.<font color='#ff0000'> Therefore, interactive multimedia learning systems are widely used to support teaching and learning.</font> Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"2.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased.<font color='#ff0000'> Therefore, interactive multimedia learning systems are widely used to support teaching and learning.</font> Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"3.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning.<font color='#ff0000'> Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention.</font> However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"4.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention.<font color='#ff0000'> However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently.</font> In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"5.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words,<font color='#ff0000'> each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems.</font> To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            //內文重點NO.6
            ,"6.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently.<font color='#ff0000'> In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems.</font> To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"7.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. <font color='#ff0000'>To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems.</font> Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"8.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems.<font color='#ff0000'> Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships.</font> More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"9.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses,<font color='#ff0000'> data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships.</font> More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"10.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. <font color='#ff0000'>Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships.</font> More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            //內文重點NO.11
            ,"11.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems.<font color='#ff0000'> Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships.</font> More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"12.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences.<font color='#ff0000'> Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.</font>  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"13.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.<font color='#ff0000'>  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme.</font> In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"14.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences. The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. <font color='#ff0000'>In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems.</font>"
            ,"15.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme. In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences.<font color='#ff0000'> The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences.</font> In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."
            ,"16.With advances in information and communication technology, the interest in incorporating multimedia into instruction has increased. Therefore, interactive multimedia learning systems are widely used to support teaching and learning. Interactive multimedia learning systems utilize several types of media, such as text, images, audio, animation and video, to attract a user’s attention. However, human factors vary across users so they may prefer the design of interactive multimedia learning systems differently. In other words, each user may appreciate the aforementioned media differently, which will, in turn, determine whether they can successfully accept and use interactive multimedia learning systems. To have a deep understanding of the influences of human factors, we apply a data mining approach to the investigation of users’ preferences in using interactive multimedia learning systems. Unlike traditional statistics, where the scope of results is restricted by the hypotheses, data mining is discovery driven in that it is not necessary to have the initial formulation of hypotheses and instead uses the data themselves to discover patterns and relationships. More specifically, a clustering technique named K-modes is used to group users’ preferences. Clustering is concerned with the division of data into groups of similar objects. Each group, called a cluster, consists of objects that are similar between themselves and dissimilar to objects of others.  Features used to create clusters include: (1) the layout of the interface, (2) the button type preferred by users, (3) the use of icons embedded within buttons, (4) the use of menus, and (5) user’s preferred color scheme.<font color='#ff0000'> In order to identify the role of human factors on determining the clusters, ANalysis Of VAriance (ANOVA) was used to obtain statistical significances of Age, Studying Levels, Computer Experience, and Gender differences.</font> The results indicated that users’ preferences could be divided into four groups, where computer experience was a key human factor that influenced their preferences. In brief, experts and novices favored different types of features provided by the interactive multimedia learning systems."

            };
    public static String reading_vocabularychinese[] = new String[]{
            "(n.) 動機性",
            "(a.) 階層式",
            "(a.) 有關聯的",
            "(adv.) 有組織地",
            "(a.) 動畫的",
            "(a.) 教育性的",
            "(prep.) 關於",
            "(n.) 觀點",
            "(n.) 論點",
            "(v.) 實施，進行",
            "(a.) 實證的",
            "(v.) 反應",
            "(n.) 準則",
            "(n.) 感知",
            "(n.) 個人",
            "(a.) 合作的",
            "(n.) 策略",
            "(v.) 探討"
    };

    public static String ArrayQues1[] = new String[]{
            "(1)Which of the following sentence is INCORRECT?",
            "(2)Which of the following sentence is INCORRECT?",
            "(3)Which of the following sentence is CORRECT?",
            "(4)Which of the following sentence is INCORRECT?",
            "(5)Which of the following sentence is CORRECT?",
            "(6)Which of the following sentence is CORRECT?",
            "(7)Which of the following sentence is INCORRECT?",
            "(8)Which of the following sentence is CORRECT?",
            "(9)Which of the following sentence is INCORRECT?",
            "(10)Which of the following sentence is CORRECT?",
            "(11)Which of the following sentence is CORRECT?",
            "(12)Which of the following sentence is INCORRECT?",
            "(13)Which of the following sentence is INCORRECT?",
            "(14)Which of the following sentence is INCORRECT?",
            "(15)Which of the following sentence is INCORRECT?",
            "(16)Which of the following sentence is INCORRECT?"
    };
    public static String[] ArrayAns1 = new String[]{ //Reading1
            //No.1
            "(a)\tIn the past days, multimedia was applied to support instruction.",
            "(b)\tMultimedia is currently applied to support instruction.",
            "(c)\tMultimedia has been applied to support instruction.",
            "(d)\tMultimedia will be applied to support instruction.",
            //No.2
            "(a)\tInteractive multimedia learning systems are widespread in educational settings.",
            "(b)\tInteractive multimedia learning systems are popular in educational settings.",
            "(c)\tInteractive multimedia learning systems are prevalent in educational settings.",
            "(d)\tInteractive multimedia learning systems are scarce in educational settings.",
            //No.3
            "(a)\tSound is excluded in interactive multimedia learning systems.",
            "(b)\tSound is not taken into account in interactive multimedia learning systems.",
            "(c)\tSound may be one type of media used in interactive multimedia learning systems.",
            "(d)\tAll media, except sound, are considered in interactive multimedia learning systems.",
            //No.4
            "(a)\tUsers may prefer the design of interactive multimedia learning systems differently because of diverse human factors.",
            "(b)\tHuman factors vary across users; nonetheless, they may prefer the design of interactive multimedia learning systems differently.",
            "(c)\tHuman factors vary across users; hence they may prefer the design of interactive multimedia learning systems differently.",
            "(d)\tUsers may prefer the design of interactive multimedia learning systems differently due to diverse human factors.",
            //No.5
            "(a)\tWhat every user values may be different.",
            "(b)\tEvery user may express “thank you” in different words.",
            "(c)\tEvery user may send a thank you note in different ways.",
            "(d)\tEvery user may express gratitude in different ways",
            //No.6
            "(a)\tIf users appreciate various media, they can accept and use interactive multimedia learning systems.",
            "(b)\tUsers appreciate various media if they can accept and use interactive multimedia learning systems.",
            "(c)\tHow various media are appreciated by users will decide if they can successfully accept and use interactive multimedia learning systems.",
            "(d)\tHow users accept and use interactive multimedia learning system will decide if they appreciate various media.",
            //No.7
            "(a)\tA data mining approach is applied to investigate users’ preferences in using interactive multimedia learning systems so a deep understanding of the influences of human factors can be acquired.",
            "(b)\tA data mining approach is applied to investigate users’ preferences in using interactive multimedia learning systems so as to obtain a deep understanding of the influences of human factors.",
            "(c)\tA data mining approach is applied to investigate users’ preferences in using interactive multimedia learning systems in order to obtain a deep understanding of the influences of human factors.",
            "(d)\tA data mining approach is applied to investigate users’ preferences in using interactive multimedia learning systems so that a deep understanding of the influences of human factors can be acquired.",
            //No.8
            "(a)\tThe scope of results is beyond the hypotheses in traditional statistics.",
            "(b)\tThe scope of results is unbounded by the hypotheses in traditional statistics.",
            "(c)\tThe broad scope of the results can be obtained from traditional statistics.",
            "(d)\tTraditional statistics potentially restrain the scope of the results.",
            //No.9
            "(a)\tData mining discovers patterns and relationships based on the data themselves.",
            "(b)\tData mining discovers patterns and relationships on the basis of the data themselves. ",
            "(c)\tData mining discovers patterns and relationships separated from the data themselves.",
            "(d)\tData mining discovers patterns and relationships extracted from the data themselves. ",
            //No.10
            "(a)\tThe rationale of traditional statistics is similar to that of data mining.",
            "(b)\tThe rationale of traditional statistics is contradictory to that of data mining.",
            "(c)\tThe rationale of traditional statistics is identical to that of data mining.",
            "(d)\tThe rationale of traditional statistics is equivalent to that of data mining.",
            //No.11
            "(a)\tData is discovery driven because there is no need to have the initial formulation of hypotheses.",
            "(b)\tData is discovery driven so there is no need to have the initial formulation of hypotheses.",
            "(c)\tData is discovery driven but there is no need to have the initial formulation of hypotheses.",
            "(d)\tData is discovery driven; moreover, there is no need to have the initial formulation of hypotheses.",
            //No.12
            "(a)\tObjects within a cluster share some heterogeneities while homogeneities exist among objects of different clusters.",
            "(b)\tEach cluster consists of miscellaneous objects while the objects of different clusters are close to each other.",
            "(c)\tThe degree of similarity between objects in the same cluster is more unsubstantial than that between objects of different clusters.",
            "(d)\tObjects within the same clusters are alike and objects of different clusters are unlike to each other.",
            //No.13
            "(a)\tSeveral features are used to create clusters, e.g., the layout of the interface and the button type.",
            "(b)\tSeveral features are used to create clusters, i.e., the layout of the interface and the button type.",
            "(c)\tSeveral features are used to create clusters, such as the layout of the interface and the button type.",
            "(d)\tFurther to the use of icons and menus, the layout of the interface and the button type are also used to create clusters.",
            //No.14
            "(a)\tExperienced users and inexperienced users reacted differently to the interactive multimedia learning systems.",
            "(b)\tExperts and novices appreciated different types of features interactive multimedia learning systems provided.",
            "(c)\tFeatures provided by interactive multimedia learning systems were valued by professionals and amateurs differently.",
            "(d)\tNovices and beginners appreciated interactive multimedia learning systems in different ways.",
            //No.15
            "(a)\tUsers in these four groups preferred different features included in interactive multimedia learning systems.",
            "(b)\tUsers with a similar level of computer experience might prefer similar features included in the interactive multimedia learning systems.",
            "(c)\tComputer experience each user had was the main issue that affected their preferences for features included in the interactive multimedia learning systems.",
            "(d)\tIndividuals’ computers experience was dissociated with their preferences for various features included in interactive multimedia learning systems.",
            //No.16
            "(a)\tThe ANOVA was employed to appraise if Studying Levels play a significant role on determining the clusters.",
            "(b)\tWhether gender differences are significant human factors are assessed by the ANOVA.",
            "(c)\tThe statistical importance of computer experience was determined by the ANOVA.",
            "(d)\tThe importance of computer experience was determined by a quantitative method.",


    };

    public static String ArrayCorrectAns1[] = new String[]{
            //No.1
            "(d)\tMultimedia will be applied to support instruction.",
            "(d)\tInteractive multimedia learning systems are scarce in educational settings.",
            "(c)\tSound may be one type of media used in interactive multimedia learning systems.",
            "(b)\tHuman factors vary across users; nonetheless, they may prefer the design of interactive multimedia learning systems differently.",
            //No.5
            "(a)\tWhat every user values may be different.",
            "(c)\tHow various media are appreciated by users will decide if they can successfully accept and use interactive multimedia learning systems.",
            "(a)\tA data mining approach is applied to investigate users’ preferences in using interactive multimedia learning systems so a deep understanding of the influences of human factors can be acquired.",
            "(d)\tTraditional statistics potentially restrain the scope of the results.",
            //No.9
            "(c)\tData mining discovers patterns and relationships separated from the data themselves. ",
            "(b)\tThe rationale of traditional statistics is contradictory to that of data mining.",
            "(a)\tData is discovery driven because there is no need to have the initial formulation of hypotheses.",
            "(d)\tObjects within the same clusters are alike and objects of different clusters are unlike to each other.",
            //No.13
            "(b)\tSeveral features are used to create clusters, i.e., the layout of the interface and the button type.",
            "(d)\tNovices and beginners appreciated interactive multimedia learning systems in different ways.",
            "(d)\tIndividuals’ computers experience was dissociated with their preferences for various features included in interactive multimedia learning systems.",
            "(c)\tThe statistical importance of computer experience was determined by the ANOVA."

    };


}
