package com.example.a2lab.studyone_12;

public class exam_ques_ans {
    public static String reading_summary1[]=new String[] {
         //reading1內文
         "Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         //中文大綱
         ,"恐怖谷理論是一個關於機械人的假設。 這項假設的論點說明當觀察者看到機械人或是其他有著模仿人類外表的東西，在外觀或是動作上極度與人類相似時，所產生的一種厭惡的反應。這個術語是一位機械專家森政宏所發明。他指出，當一個機械人在外表和動作上越來越像人類時，觀察者對於機器人的正面情緒以及移情作用會不斷增加，直到某一個程度時，觀察者反應會突然變得極之反感。然而，當其外觀和動作變得與人類越來越難分辨時，觀察者對其情感亦再次變回正面，且貼近人類與人類之間的移情作用。恐怖谷理論的真實性在一次最新研究中被檢視。研究中給五隻猴子三種不同的圖片：兩張不同3D建模的猴子臉圖案（一張做的很真，一張不是）、以及一張真實猴子臉的圖片。而牠們眼睛注視的時間被視為整項結果的判定標準。由於做的很真的3D建模猴子臉圖被注視的時間比其他兩張圖片還短，這顯示了，參與實驗的猴子對做的很真的3D建模猴子臉圖厭惡，或是牠們比較喜歡另外兩張圖。電影產業正經地看待恐怖谷理論，因為它會造成民眾對動畫人類的反感。為了盡可能避免恐怖谷的發生，動畫師會採取一些方式。例如，設計出來的人物需包含真人的特徵。換句話說，當一個動畫角色外觀上比他的行為更像人類時，就會給予反感。同時混了真人和非人特徵的動畫人類可能看起來很怪異，而這是動畫師必須避開的。這樣才能確保大部分的觀眾能有一個愉快的看電影經驗。"
         //內文重點NO.1
         ,"1.\n<font color='#ff0000'>Nowadays</font>, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"2.<font color='#ff0000'>Nowadays, Web-based learning (WBL) </font>systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"3.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"4.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"5.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         //內文重點NO.6
         ,"6.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"7.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"8.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"9.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"10.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
            //內文重點NO.11
         ,"11.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"12.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"13.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"14.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"15.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."
         ,"16.Nowadays, Web-based learning (WBL) systems have become popular because they provide high flexibility. In particular, learners are allowed to use multiple tools, among which hierarchical maps are widely used to support teaching and learning. This is due to the fact that learners can acquire an overall picture from the hierarchical maps. Such an overall picture is beneficial for learners to build the global understanding of the subject content. However, traditional hierarchical maps may let learners easily get lost within large information space. Thus, learners may find it difficult to discover relevant issues if information is not systematically displayed in the hierarchical maps. This study proposes an animated hierarchical map to address this problem. On the other hand, there are two instructional approaches, i.e. individual learning and collaborative learning. Regarding individual learning, a learner develops learning strategies on his/her own. Regarding collaborative learning, learners work together to develop their learning strategies so they can exchange ideas, perspectives, and arguments with each other. The differences between these two approaches lie within the fact that individual learning is the one in which learners work individually to reach their own objectives while collaborative learning is an instruction method in which more than an individual work together to reach their common objectives. Because of such differences, we also conducted an empirical study to examine how learners in collaborative learning and those in individual learning reacted differently to the animated hierarchical map and traditional hierarchical map. A questionnaire, which was designed based on Nielsen’s heuristics, was applied to examine learners’ reactions to the proposed animated hierarchical map. This is owing to the fact that the questionnaire is useful to investigate learners’ perception. The results show that the proposed animated hierarchical map is generally better than the traditional hierarchical map but the effects on individual learning is limited. In other words, the effects of the proposed map on individual learning are not as obvious as collaborative learning."

            };
    public static String reading_vocabularychinese[] = new String[]{
            "(adj.)\t上述的",//1
            "(n.)\t動畫",//2
            "(v.)\t感激，賞識",//3
            "(n.)\t方法",//4
            "(v.)\t吸引",//5
            "(n.)\t群集",//6
            "(n.)\t溝通",//7
            "(n.)\t關心",//8
            "(v.)\t發現",//9
            "(adj.)\t不相同的",//10
            "(n.)\t區分",//11
            "(n.)\t因素",//12
            "(n.)\t形成",//13
            "(n.)\t假說",//14
            "(v.)\t證明，確認",//15
            "(片語)\t依次",//16
            "(v.)\t合併",//17
            "(v.)\t顯示，指出",//18
            "(adj.)\t初始的",//19
            "(n.)\t教育，指示",//20
            "(adj.)\t互動的",//21
            "(n.)\t調查，研究",//22
            "(n.)\t多媒體",//23
            "(n.)\t初學者",//24
            "(n.)\t物件",//25
            "(n.)\t形式",//26
            "(n.)\t偏愛，偏好",//27
            "(adj.)\t受限制的",//28
            "(n.)\t方案",//29
            "(n.)\t範圍，廣度",//30
            "(n.)\t重要性，含義",//31
            "(adj.)\t統計的",//32
            "(n.)\t類型",//33
            "(v.)\t利用",//34
            "(v.)\t改變",//35
    };

    public static String ArrayQues1[] = new String[]{
            "(1)Which of the following sentence is INCORRECT?",
            "(2)Which of the following sentence is INCORRECT?",
            "(3)Which of the following sentence is CORRECT?",
            "(4)Which of the following sentence is CORRECT?",
            "(5)Which of the following sentence is CORRECT?",
            "(6)Which of the following sentence is INCORRECT?",
            "(7)Which of the following sentence is INCORRECT?",
            "(8)Which of the following sentence is INCORRECT?",
            "(9)Which of the following sentence is CORRECT?",
            "(10)Which of the following sentence is CORRECT?",
            "(11)Which of the following sentence is CORRECT?",
            "(12)Which of the following sentence is CORRECT?",
            "(13)Which of the following sentence is CORRECT?",
            "(14)Which of the following sentence is INCORRECT?",
            "(15)Which of the following sentence is CORRECT?",
            "(16)Which of the following sentence is CORRECT?"
    };
    public static String[] ArrayAns1 = new String[]{ //Reading1
            //No.1
            "(a)In the past days, Web-based learning systems were popular.",
            "(b)Web-based learning systems are currently popular.",
            "(c)Web-based learning systems have grown in popularity.",
            "(d)Web-based learning systems will become popular in the future.",
            //No.2
            "(a)Web-based learning (WBL) systems provide various tools.",
            "(b)Tools provided by Web-based learning (WBL) systems lack diversity.",
            "(c)A variety of tools are provided by Web-based learning (WBL) systems.",
            "(d)More than one tool is offered Web-based learning (WBL) systems.",
            //No.3
            "(a)Rare tools are provided by Web-based learning (WBL) systems.",
            "(b)Web-based learning (WBL) systems provide few tools.",
            "(c)Web-based learning (WBL) systems provide insufficient tools.",
            "(d)A number of tools are provided by Web-based learning (WBL) systems.",
            //No.4
            "(a)Hierarchical maps are only tools provided by Web-based learning (WBL) systems.",
            "(b)In addition to hierarchical maps, Web-based learning (WBL) systems also offer other tools.",
            "(c)Apart from Hierarchical maps, tools provided by Web-based learning (WBL) systems are useful to support teaching and learning.",
            "(d)Tools offered by Web-based learning (WBL) systems are useful to support teaching and learning, except hierarchical maps.",
            //No.5
            "(a)The hierarchical maps can hinder learners to get an overall picture.",
            "(b)The hierarchical maps were disadvantageous for learner to build the global understandings.",
            "(c)The hierarchical map can facilitate learners to obtain the entire picture of the subject matter.",
            "(d)It is the shortcoming of the hierarchical maps that learners can get an overview of the subject content.",
            //No.6
            "(a)It may be hard for learners to identify relevant issues with traditional hierarchical maps.",
            "(b)Traditional hierarchical maps may make learners experience fewer disorientation problems.",
            "(c)Finding relevant issues with traditional hierarchical maps might be a difficult task.",
            "(d)Learners may encounter disorientation problems when they use traditional hierarchical maps.",
            //No.7
            "(a)Information should be chaotically presented in the hierarchical maps, lest learners can find relevant issues.",
            "(b)Messy information displayed in the hierarchical maps may make learners difficult to find relevant issues.",
            "(c)Information presented in the hierarchical maps needs to be well organized so that learners can find relevant issues.",
            "(d)Information needs to be presented in a systematic way for the feat that relevant issues cannot be discovered.",
            //No.8
            "(a)To address the problem of the traditional hierarchical map, the authors undertook an empirical study.",
            "(b)Further to individual learning, collaborative learning is another instructional approach.",
            "(c)The animated hierarchical map might have dissimilar effects on collaborative learning and individual learning.",
            "(d)The animated hierarchical map might have potential to sort out the problem of the traditional hierarchical maps.",
            //No.9
            "(a)Collaborative learning can facilitate learners to develop their learning strategies by themselves.",
            "(b)Collaborative learning can help learners acquire additional thoughts from their peers.",
            "(c)It is necessary for learners to share objectives in the context of individual learning.",
            "(d)There is no need to identify identical objectives in the context of collaborative learning.",
            //No.10
            "(a)Individual learning is useful for learners to develop their learning strategies autonomously.",
            "(b)Individual learning can help learners obtain advice from their companions.",
            "(c)Sharing objectives is trivial, regardless of individual learning or collaborative learning.",
            "(d)It is imperative to identify diverse objectives in the context of collaborative learning.",
            //No.11
            "(a)Learners' reactions to the proposed animated hierarchical map were examined by a questionnaire that is useful to investigate learners’ perception.",
            "(b)Learners' reactions to the proposed animated hierarchical map were examined by a questionnaire which is useful to investigate learners’ perception.",
            "(c)A questionnaire is useful to investigate learners' perception though it was employed to examine learners’ reactions to the proposed animated hierarchical map.",
            "(d)A questionnaire is useful to investigate learners' perception; consequently, it was employed to examine learners’ reactions to the proposed animated hierarchical map.",
            //No.12
            "(a)Absolutely, the proposed animated hierarchical map is better than the traditional hierarchical map.",
            "(b)Without any doubts, the proposed animated hierarchical map is better than the traditional hierarchical map.",
            "(c)By and large, the proposed animated hierarchical map is better than the traditional hierarchical map.",
            "(d)Unquestionably, the proposed animated hierarchical map is better than the traditional hierarchical map.",
            //No.13
            "(a)Generally, the traditional hierarchical map is not worse than the proposed animated hierarchical map.",
            "(b)Generally, the proposed animated hierarchical map is superior to the traditional hierarchical map.",
            "(c)Generally, the proposed animated hierarchical map is as good as the traditional hierarchical map.",
            "(d)Generally, the proposed animated hierarchical map is less great than the traditional hierarchical map.",
            //No.14
            "(a)Like collaborative learning, the proposed animated hierarchical map has considerable effects on individual learning.",
            "(b)Individual learning and collaborative learning benefit from the proposed animated hierarchical map differently.",
            "(c)The effects of the proposed animated hierarchical map on individual learning are not as apparent as those on collaborative learning.",
            "(d)The effects that the proposed animated hierarchical map has on individual learning are not in agreement with collaborative learning.",
            //No.15
            "(a)The proposed animated hierarchical map has comparable effects on individual learning and collaborative learning.",
            "(b)The effects that the proposed animated hierarchical map has on individual learning are inconsistent with those on collaborative learning.",
            "(c)The proposed animated hierarchical map has homogeneous effects on individual learning and collaborative learning.",
            "(d)The effects of the proposed animated hierarchical map on individual learning are as evident as collaborative learning.",
            //No.16
            "(a)The effects that the proposed animated hierarchical map has on individual learning are not coherent with those on collaborative learning.",
            "(b)Generally, the proposed animated hierarchical map is as bad as the traditional hierarchical map.",
            "(c)The proposed animated hierarchical map is inferior to the traditional hierarchical map.",
            "(d)The proposed animated hierarchical map is completely better than the traditional hierarchical map.",


    };

    public static String ArrayCorrectAns1[] = new String[]{
            //No.1
            "(d)Web-based learning systems will become popular in the future.",
            "(b)Tools provided by Web-based learning (WBL) systems lack diversity.",
            "(d)A number of tools are provided by Web-based learning (WBL) systems.",
            "(b)In addition to hierarchical maps, Web-based learning (WBL) systems also offer other tools.",
            //No.5
            "(c)The hierarchical map can facilitate learners to obtain the entire picture of the subject matter.",
            "(b)Traditional hierarchical maps may make learners experience fewer disorientation problems.",
            "(a)Information should be chaotically presented in the hierarchical maps, lest learners can find relevant issues.",
            "(a)To address the problem of the traditional hierarchical map, the authors undertook an empirical study.",
            //No.9
            "(b)Collaborative learning can help learners acquire additional thoughts from their peers.",
            "(a)Individual learning is useful for learners to develop their learning strategies autonomously.",
            "(d)A questionnaire is useful to investigate learners' perception; consequently, it was employed to examine learners’ reactions to the proposed animated hierarchical map.",
            "(c)By and large, the proposed animated hierarchical map is better than the traditional hierarchical map.",
            //No.13
            "(b)Generally, the proposed animated hierarchical map is superior to the traditional hierarchical map.",
            "(a)Like collaborative learning, the proposed animated hierarchical map has considerable effects on individual learning.",
            "(b)The effects that the proposed animated hierarchical map has on individual learning are inconsistent with those on collaborative learning.",
            "(a)The effects that the proposed animated hierarchical map has on individual learning are not coherent with those on collaborative learning."

    };


}
